language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - build-tools-23.0.1
    - doc # Just the package-list is needed for JavaDoc task; OK to fetch the latest version here.

    - extra-android-m2repository # Exact version specified in gradle.properties; OK to fetch latest version here.

    - android-8
    - android-22
    - sys-img-armeabi-v7a-android-22
    - android-23
  licenses:
    - 'android-sdk-license-.*'

env:
  matrix:
    # Ideally, the matrix would run against 8, 10, 19, 22, 23.  However that
    # takes too long and CI builds are flaky enough to make all the different
    # sets of tests unlikely to succeed.  So the min and max are tested as an
    # optimization.  Note that android-23 currently hangs in CI, so 22 is tested
    # instead.
    - AVD_API_LEVEL=android-8
    - AVD_API_LEVEL=android-22

before_script:
  - echo no | android create avd --force -n test --target $AVD_API_LEVEL
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - sleep 30
  - adb shell input keyevent 82 &

script:
  - adb logcat > logcat.txt & # write logs to a file, to make test failure debugging easier
  - TERM=dumb ./gradlew -PIS_PREDEXING_ENABLED=false assemble connectedCheck check findbugs releaseJavadoc --stacktrace

after_failure:
  - cat logcat.txt
